---
- name: Build hello
  include: build.yml
  tags:
    - build

- name: Deploy hello
  include: deploy.yml
  become: yes
  tags:
    - deploy

- name: Test hello
  include: test.yml
  tags:
    - test
